version : "3"
services: 
  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  
      # ro (read only), docker container can not change into file-system, https://docs.docker.com/storage/volumes/#use-a-read-only-volume 
  node-app-container:
    build: .
    # ports: 
    #   - "4000-4001:5000"
    environment: 
      - PORT=5000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - mongo-db:/data/db
  redis: 
    image: redis

# create a named volume where the data will be stored
volumes: 
  mongo-db:




