version : "3"
services: 
  nginx:
    ports:
      - "80:80"
  node-app-container:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - SESSION_SECRET=secret
    command: node index.js
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root